blog/urls.py
from django.urls import path
from .views import IndexView, BlogDetailView, AuthorView

app_name = 'blog'


urlpatterns = [
    path('',IndexView.as_view(), name='index'),
    path('story/<slug:slug>/',BlogDetailView.as_view(), name='blog-detail'),
    path('author/',AuthorView.as_view(), name='author'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemap import BlogSitemap, CategorySitemap
from django.contrib.admin.sites import AdminSite
from django.shortcuts import redirect

# class MyAdminSite(AdminSite):

#     def check_admin(self, request):
#         if request.user == request.user.is_authenticated():
#             return redirect('manage/admin/')
#         else:
#             return redirect('index')

#     def get_urls(self):
#         urls = super().get_urls()
#         urls += [
#             path('manage/admin/', self.admin_view(self.check_admin))
#         ]
#         return urls

sitemaps = {
    'blog':BlogSitemap,
    'category':CategorySitemap
}

urlpatterns = [
    # path('manage/admin/',MyAdminSite.get_urls),
    path('manage/admin/',admin.site.urls),
] + i18n_patterns(
    path('i18n/',include('django.conf.urls.i18n')),
    path('',include('blog.urls'), name=settings.LANGUAGES),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Ravshanbek Madaminov's Page AdminPanel"
admin.site.site_title = "Admin"

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.utils.text import slugify
from .signals import add_gpt_response

class Category(models.Model):
    name = models.CharField(max_length=25)
    slug = models.SlugField(blank=True, null=True)

    class Meta:
        verbose_name_plural = "Category"

    def __str__(self):
        return self.name

class Blog(models.Model):
    title = models.CharField(max_length=120)
    subtitle = models.CharField(max_length=70)
    slug = models.SlugField(blank=True, null=True)
    body = RichTextField(blank=True)
    preview_image = models.FileField()
    category = models.ManyToManyField(Category, related_name='blogs')
    meta_description = models.CharField(max_length=150)
    views = models.IntegerField(default=0)
    added_date = models.DateField(auto_now_add=True)
    estimated_read_time = models.IntegerField(default=2)

    class Meta:
        verbose_name_plural = "Blog"

    def __str__(self):
        return self.title
    
@receiver(post_save, sender=Category)
def post_save_category(instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.name)
        instance.save()
    
@receiver(post_save, sender=Blog)
def pre_save_blog(instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.title)
        instance.save()

add_gpt_response(instance=Blog)

blog/views.py
from django.shortcuts import render
from django.views import View

from .models import Blog, Category
from .utils import searchBlogs, paginateBlogs

class IndexView(View):
    def get(self, request):
        blogs, search_query = searchBlogs(request)
        popular_blogs = blogs.order_by('views')[:2]
        categories_query = Category.objects.all()
        # paginate blogs
        custom_range, blogs = paginateBlogs(request, blogs, 12)
        context = {
            'categories':categories_query,
            'blogs':blogs,
            'search_query':search_query,
            'custom_range':custom_range,
            'popular_blogs':popular_blogs
        }
        return render(request, 'blog/index.html', context)
     
class BlogDetailView(View):
    def get(self, request, slug):
        blog = Blog.objects.get(slug=slug)
        blog.views += 1
        blog.save()
        blogs = Blog.objects.filter(category__name=blog.category.first()).exclude(slug=blog.slug)[:3]
        context = {
            'blog':blog,
            'blogs':blogs
        }

        return render(request, 'blog/post.html', context)
    
class AuthorView(View):
    def get(self, request):
        return render(request, 'blog/author.html')
    
# class FilterCategoriesView(View):
#     def get(self, request, category):
#         query_categories = Category.objects.filter()
#         return render(request, 'category-navbar.html')

blog/templates/blog/author.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block meta %}
<meta name="description" content="About author">
<meta name="author" content="Ravshanbek Madaminov">
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<!-- Begin Top Author Page
================================================== -->
<div class="container">
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-8 col-md-offset-2">
			<div class="mainheading">
				<div class="row post-top-meta authorpage">
					<div class="col-md-10 col-xs-12">
						<h1>Ravshanbek Madaminov</h1>
						<span class="author-description"><a target="_blank" href="https://www.medwait.com/">{% blocktrans %}Founder of MedWait</a> and <strong>Software engineer</strong> with 1.5 years of experience{% endblocktrans %} </span>
						<span class="col"><a href="https://www.github.com/ravshanbekio/">{% blocktrans %}Github page{% endblocktrans %}</a></span>
						<!-- <div class="sociallinks"><a  target="_blank" href="https://www.facebook.com/wowthemesnet/"><i class="fa fa-facebook"></i></a> <span class="dot"></span> <a target="_blank" href="https://plus.google.com/s/wowthemesnet/top"><i class="fa fa-google-plus"></i></a></div> -->
					</div>
					<div class="col-md-2 col-xs-12">
						<img class="author-thumb" src="{% static 'assets/img/profile_image.JPG' %}" alt="Sal">
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- End Top Author Meta
================================================== -->
{% endblock content %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block meta %}
<meta name="description" content="">
<meta name="author" content="Ravshanbek Madaminov">
{% endblock meta %}

{% block content %}

{% include 'navbar.html' %}
    
<!-- Begin Site Title
================================================== -->
<div class="container">
	<div class="mainheading">
		<h1 class="sitetitle">Ravshanbek's Blog</h1>
		<p class="lead">
			{% blocktrans %}Tips, instructions and video tutorials for dreamers{% endblocktrans %}
		</p>
	</div>
<!-- End Site Title
================================================== -->

	<!-- Begin List Posts
	================================================== -->
	<section class="recent-posts">
		<div class="section-title">
			<h2><span>{% blocktrans %}Popular Stories{% endblocktrans %}</span></h2>
		</div>
		<div class="card-columns listrecent">
			{% for popular_blog in popular_blogs %}
				<!-- begin post -->
				<div class="card">
					<a href="{% url 'blog:blog-detail' popular_blog.slug %}">
						<img class="img-fluid" src="{{ popular_blog.preview_image.url }}" alt="">
					</a>
					<div class="card-block">
						<h2 class="card-title"><a href="{% url 'blog:blog-detail' popular_blog.slug %}">{{ popular_blog.title }}</a></h2>
						<h4 class="card-text">{{ popular_blog.subtitle }}</h4>
						<div class="metafooter">
							<div class="wrapfooter">
								<span class="meta-footer-thumb">
								</span>
								<span class="author-meta">
								<span class="post-date">{{ popular_blog.added_date }}</span><span class="dot"></span><span class="post-read">{{ puplar_blog.estimated_read_time }} min read</span>
								</span>
							</div>
						</div>
					</div>
				</div>
				<!-- end post -->
			{% endfor %}

		</div>
		<div class="section-title">
			<h2><span>{% blocktrans %}All Stories{% endblocktrans %}</span></h2>
		</div>
		<div class="card-columns listrecent">
			{% for blog in blogs %}
				<!-- begin post -->
				<div class="card">
					<a href="{% url 'blog:blog-detail' blog.slug %}">
						<img class="img-fluid" src="{{ blog.preview_image.url }}" alt="">
					</a>
					<div class="card-block">
						<h2 class="card-title"><a href="{% url 'blog:blog-detail' blog.slug %}">{{ blog.title }}</a></h2>
						<h4 class="card-text">{{ blog.subtitle }}</h4>
						<div class="metafooter">
							<div class="wrapfooter">
								<span class="meta-footer-thumb">
								</span>
								<span class="author-meta">
								<span class="post-date">{{ blog.added_date }}</span><span class="dot"></span><span class="post-read">{{ blog.estimated_read_time }} min read</span>
								</span>
							</div>
						</div>
					</div>
				</div>
				<!-- end post -->
			{% endfor %}

		</div>
	</section>
	<!-- End List Posts
	================================================== -->

	<nav aria-label="Page navigation example">
			<ul class="pagination justify-content-center">

				{% if blogs.has_previous %}
					<li><a href="?page={{blogs.previous_page_number}}" class="btn page-link"
							data-page="{{blogs.previous_page_number}}">&#10094; {% blocktrans %}Prev{% endblocktrans %}</a></li>
				{% endif %}


				{% for page in custom_range %}

					{% if page == blogs.number%}
					<li><a href="?page={{page}}" class="btn page-link btn--sub" data-page="{{page}}">{{page}}</a></li>
					{% else %}
					<li><a href="?page={{page}}" class="btn page-link" data-page="{{page}}">{{page}}</a></li>
					{% endif %}
				{% endfor %}

				{% if blogs.has_next %}
					<li><a href="?page={{blogs.next_page_number}}" class="btn page-link"
							data-page="{{blogs.next_page_number}}">{% blocktrans %}Next{% endblocktrans %} &#10095;</a></li>
				{% endif %}

			</ul>
	</nav>
	

{% endblock content %}

blog/templates/blog/post.html
{% extends 'base.html' %}
{% load i18n %}
{% load social_share %}

{% block title %}
<title>{{ blog.title }}</title>
{% endblock title %}

{% block meta %}
<meta name="description" content="{{ blog.meta_description }}">
<meta name="author" content="Ravshanbek Madaminov">
{% endblock meta %}

{% block content %}

{% include 'navbar.html' %}
<!-- Begin Article
================================================== -->
<div class="container">
	<div class="row">

		<div class="col-md-2 col-xs-12">
			<div class="share">
				<p>
					Share
				</p>
				<ul>
					<li>
						{% post_to_facebook object_or_url "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512'><path d='M504 256C504 119 393 8 256 8S8 119 8 256c0 123.78 90.69 226.38 209.25 245V327.69h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.28c-30.8 0-40.41 19.12-40.41 38.73V256h68.78l-11 71.69h-57.78V501C413.31 482.38 504 379.78 504 256z'/></svg>" %}
					</li>
					<li>
						{% post_to_twitter "Useful blog: {{ object.title }}. Check it out!" object_or_url "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512'><path d='M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z'/></svg>" %}
					</li>
					<li>
						{% post_to_telegram "Useful blog: {{ object.title }}. Check it out!" object_or_url "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 496 512'><path d='M248,8C111.033,8,0,119.033,0,256S111.033,504,248,504,496,392.967,496,256,384.967,8,248,8ZM362.952,176.66c-3.732,39.215-19.881,134.378-28.1,178.3-3.476,18.584-10.322,24.816-16.948,25.425-14.4,1.326-25.338-9.517-39.287-18.661-21.827-14.308-34.158-23.215-55.346-37.177-24.485-16.135-8.612-25,5.342-39.5,3.652-3.793,67.107-61.51,68.335-66.746.153-.655.3-3.1-1.154-4.384s-3.59-.849-5.135-.5q-3.283.746-104.608,69.142-14.845,10.194-26.894,9.934c-8.855-.191-25.888-5.006-38.551-9.123-15.531-5.048-27.875-7.717-26.8-16.291q.84-6.7,18.45-13.7,108.446-47.248,144.628-62.3c68.872-28.647,83.183-33.623,92.511-33.789,2.052-.034,6.639.474,9.61,2.885a10.452,10.452,0,0,1,3.53,6.716A43.765,43.765,0,0,1,362.952,176.66Z'/></svg>" %}
					</li>
				</ul>
				<div class="sep">
				</div>
				<ul>
					<li>
					<a href="#comments">
					42<br/>
					<svg class="svgIcon-use" width="29" height="29" viewbox="0 0 29 29"><path d="M21.27 20.058c1.89-1.826 2.754-4.17 2.754-6.674C24.024 8.21 19.67 4 14.1 4 8.53 4 4 8.21 4 13.384c0 5.175 4.53 9.385 10.1 9.385 1.007 0 2-.14 2.95-.41.285.25.592.49.918.7 1.306.87 2.716 1.31 4.19 1.31.276-.01.494-.14.6-.36a.625.625 0 0 0-.052-.65c-.61-.84-1.042-1.71-1.282-2.58a5.417 5.417 0 0 1-.154-.75zm-3.85 1.324l-.083-.28-.388.12a9.72 9.72 0 0 1-2.85.424c-4.96 0-8.99-3.706-8.99-8.262 0-4.556 4.03-8.263 8.99-8.263 4.95 0 8.77 3.71 8.77 8.27 0 2.25-.75 4.35-2.5 5.92l-.24.21v.32c0 .07 0 .19.02.37.03.29.1.6.19.92.19.7.49 1.4.89 2.08-.93-.14-1.83-.49-2.67-1.06-.34-.22-.88-.48-1.16-.74z"></path></svg>
					</a>
					</li>
				</ul>
			</div>
		</div>
		<!-- End Fixed Left Share -->

		<!-- Begin Post -->
		<div class="col-md-8 col-md-offset-2 col-xs-12">
			<div class="mainheading">
				<h1 class="posttitle">{{ blog.title }}</h1>
				<p class="text-secondary">{% blocktrans %}Posted on {% endblocktrans %} {{ blog.added_date }}</p>
			</div>

			<!-- Begin Featured Image -->
			<img class="featured-image img-fluid" src="{{ blog.preview_image.url }}" alt="">
			<!-- End Featured Image -->

			<!-- Begin Post Content -->
			<div class="article-post">
				{{ blog.body|safe|linebreaks }}
			</div>
			<!-- End Post Content -->

			<!-- Begin Tags -->
			<div class="after-post-tags">
				<ul class="tags">
					{% for category in blog.category.all %}
						<li><a href="#">{{ category.name }}</a></li>
					{% endfor %}
				</ul>
			</div>
			<!-- End Tags -->

		</div>
		<!-- End Post -->

	</div>
</div>
<!-- End Article
================================================== -->

<div class="hideshare"></div>

<!-- Begin Related
================================================== -->
<div class="graybg">
	<div class="container">
		<h3>{% blocktrans %}Related{% endblocktrans %}</h3>
		<div class="row listrecent listrelated">
            {% for blog in blogs %}
                <!-- begin post -->
                <div class="col-md-4">
                    <div class="card">
                        <a href="{% url 'blog:blog-detail' blog.slug %}">
                        <img class="img-fluid img-thumb" src="{{ blog.preview_image.url }}" alt="">
                        </a>
                        <div class="card-block">
                            <h2 class="card-title"><a href="{% url 'blog:blog-detail' blog.slug %}">{{ blog.title }}</a></h2>
                            <div class="metafooter">
                                <div class="wrapfooter">
                                    <span class="meta-footer-thumb">
                                    </span>
                                    <span class="author-meta">
                                    <span class="post-date">{{ blog.added_date }}</span><span class="dot"></span><span class="post-read">{{ blog.estimated_read_time }} min read</span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end post -->
            {% endfor %}
		</div>
	</div>
</div>
<!-- End Related Posts
================================================== -->

<!-- Begin AlertBar
================================================== -->
<!-- <div class="alertbar">
	<div class="container text-center">
		<img src="assets/img/logo.png" alt=""> &nbsp; Never miss a <b>story</b> from us, get weekly updates in your inbox. <a href="#" class="btn subscribe">Get Updates</a>
	</div>
</div> -->
<!-- End AlertBar
================================================== -->

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    {% load i18n %}
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
{% block meta %}

{% endblock meta %}
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/img/demopic/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/img/demopic/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/img/demopic/favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'assets/img/demopic/site.webmanifest' %}">
{% block title %}
<title>{% blocktrans %}Ravshanbek's Blog - About Technology and Programming!{% endblocktrans %}</title>
{% endblock title %}
<!-- Bootstrap core CSS -->
<link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
<!-- Fonts -->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Righteous%7CMerriweather:300,300i,400,400i,700,700i" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="{% static 'assets/css/mediumish.css' %}" rel="stylesheet">
</head>
<body>

    {% block content %}

    {% endblock content %}


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3102758665278121"
        crossorigin="anonymous"></script>
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/ie10-viewport-bug-workaround.js' %}"></script>
    <script src="{% static 'assets/js/mediumish.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/navbar.html
{% load i18n %}
<!-- Begin Nav
================================================== -->
<nav class="navbar navbar-toggleable-md navbar-light bg-white fixed-top mediumnavigation">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="container">
        <!-- Begin Logo -->
        <a class="navbar-brand" href="{% url 'blog:index' %}">
        </a>
        <!-- End Logo -->
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <!-- Begin Menu -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                <a class="nav-link" href="{% url 'blog:index' %}">{% blocktrans %}Stories{% endblocktrans %}</a>
                </li>
                <li class="nav-item active">
                <a class="nav-link" href="{% url 'blog:author' %}">{% blocktrans %}Author{% endblocktrans %}</a>
                </li>
            </ul>
            <!-- End Menu -->
            <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                <input type="hidden" name="next" value="{{ redirect_to }}">
                <select name="language">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                        <option value="{{ language.code }}"{% if languange.code == LANGUAGE_CODE %} selected {% endif %}>
                            {{ language.name_local }} {{ language.code }}
                        </option>
                    {% endfor %}
                </select>
                <input type="submit" class="btn btn-primary" value={% blocktrans %}"Go"{% endblocktrans %}>
            </form>
            <!-- Begin Search -->
            <form class="form-inline my-2 my-lg-0" action="{% url 'blog:index' %}">
                <input class="form-control mr-sm-2" type="text" name="search_query" placeholder="Search">
                <span class="search-icon"><svg class="svgIcon-use" width="25" height="25" viewbox="0 0 25 25"><path d="M20.067 18.933l-4.157-4.157a6 6 0 1 0-.884.884l4.157 4.157a.624.624 0 1 0 .884-.884zM6.5 11c0-2.62 2.13-4.75 4.75-4.75S16 8.38 16 11s-2.13 4.75-4.75 4.75S6.5 13.62 6.5 11z"></path></svg></span>
            </form>
            <!-- End Search -->
        </div>
    </div>
</nav>
    <!-- End Nav
    ================================================== -->
    